"use client"

import Link from "next/link"
import { useEffect, useRef, useState } from "react"

// SVG icons for features
const PanIndiaIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M20.893 13.393l-1.135-1.135a2.252 2.252 0 01-.421-.585l-1.08-2.16a.414.414 0 00-.663-.107.827.827 0 01-.812.21l-1.273-.363a.89.89 0 00-.738 1.595l.587.39c.59.395.674 1.23.172 1.732l-.2.2c-.212.212-.33.498-.33.796v.41c0 .409-.11.809-.32 1.158l-1.315 2.191a2.11 2.11 0 01-1.81 1.025 1.055 1.055 0 01-1.055-1.055v-1.172c0-.92-.56-1.747-1.414-2.089l-.655-.261a2.25 2.25 0 01-1.383-2.46l.007-.042a2.25 2.25 0 01.29-.787l.09-.15a2.25 2.25 0 012.37-1.048l1.178.236a1.125 1.125 0 001.302-.795l.208-.73a1.125 1.125 0 00-.578-1.315l-.665-.332-.091.091a2.25 2.25 0 01-1.591.659h-.18c-.249 0-.487.1-.662.274a.931.931 0 01-1.458-1.137l1.411-2.353a2.25 2.25 0 00.286-.76m11.928 9.869A9 9 0 008.965 3.525m11.928 9.868A9 9 0 118.965 3.525" />
  </svg>
)

const CompanyIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
  </svg>
)

const QualityIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" />
  </svg>
)

const TalentIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
  </svg>
)

const features = [
  { icon: <PanIndiaIcon />, label: "Pan-India Reach" },
  { icon: <CompanyIcon />, label: "25+ Companies" },
  { icon: <QualityIcon />, label: "Quality Hiring" },
  { icon: <TalentIcon />, label: "15,000+ Professionals" }
]

export default function About() {
  const [isVisible, setIsVisible] = useState(false)
  const sectionRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true)
        }
      },
      { threshold: 0.2 }
    )

    if (sectionRef.current) {
      observer.observe(sectionRef.current)
    }

    return () => observer.disconnect()
  }, [])

  return (
    <section ref={sectionRef} className="bg-white py-24 overflow-hidden">
      <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-16 items-center">

        {/* Left images with staggered animation */}
        <div className="grid grid-cols-2 gap-6">
          <div
            className={`row-span-2 rounded-2xl overflow-hidden h-[420px] transition-all duration-1000 hover:scale-[1.02] relative group ${isVisible ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-20"}`}
            style={{
              boxShadow: isVisible ? "0 0 30px rgba(57,255,20,0.2)" : "none",
            }}
          >
            {/* Header Image: Generated by AI (saved as /public/images/corporate-team.png) */}
            <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-all z-10" />
            <img src="/images/corporate-team.png" alt="Corporate Team" className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" />
          </div>

          <div
            className={`rounded-2xl overflow-hidden h-[200px] transition-all duration-1000 delay-200 hover:scale-[1.05] relative group ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 -translate-y-10"}`}
          >
            {/* Header Image: Generated by AI (saved as /public/images/tech-office.png) */}
            <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-all z-10" />
            <img src="/images/tech-office.png" alt="Tech Office" className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" />
          </div>

          <div
            className={`rounded-2xl overflow-hidden h-[200px] transition-all duration-1000 delay-400 hover:scale-[1.05] relative group ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"}`}
            style={{
              boxShadow: "0 0 30px rgba(57,255,20,0.4)"
            }}
          >
            {/* Header Image: Generated by AI (saved as /public/images/industrial-worker.png) */}
            <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-all z-10" />
            <img src="/images/industrial-worker.png" alt="Industrial Worker" className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" />
          </div>
        </div>

        {/* Right content */}
        <div>
          <p
            className={`font-semibold mb-3 text-2xl tracking-wide transition-all duration-700 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
              }`}
            style={{ color: "#39FF14" }}
          >
            About SHYNR
          </p>

          <h2
            className={`text-black text-4xl md:text-5xl font-bold mb-6 transition-all duration-700 delay-100 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
              }`}
          >
            Your Trusted <br />
            Workforce Partner
          </h2>

          <p
            className={`text-gray-600 mb-8 max-w-lg transition-all duration-700 delay-200 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
              }`}
          >
            SHYNR Private Limited is a fast-growing business services organization delivering
            recruitment, workforce solutions, and managed services to clients across BFSI, IT/ITES,
            Retail, E-commerce, Telecom, and Education sectors.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-10">
            {features.map((feature, index) => (
              <div
                key={feature.label}
                className={`flex items-center gap-4 p-3 rounded-lg transition-all duration-500 hover:scale-105 cursor-pointer group ${isVisible ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-10"
                  }`}
                style={{
                  transitionDelay: `${300 + index * 100}ms`,
                  backgroundColor: "rgba(57,255,20,0.05)"
                }}
              >
                <div
                  className="w-12 h-12 rounded-full flex items-center justify-center transition-all duration-300 group-hover:scale-110"
                  style={{
                    backgroundColor: "rgba(57,255,20,0.15)",
                    boxShadow: "0 0 15px rgba(57,255,20,0.2)",
                    color: "#39FF14"
                  }}
                >
                  {feature.icon}
                </div>
                <span className="font-semibold text-black">{feature.label}</span>
              </div>
            ))}
          </div>

          {/* CTA with neon glow */}
          <Link
            href="/about/company"
            className={`inline-flex items-center gap-2 px-8 py-3 rounded-md font-semibold transition-all duration-500 hover:scale-105 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
              }`}
            style={{
              backgroundColor: "#39FF14",
              color: "#0a0a0a",
              boxShadow: "0 0 20px rgba(57,255,20,0.4), 0 0 40px rgba(57,255,20,0.2)",
              transitionDelay: "700ms"
            }}
          >
            Learn More About Us
            <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </Link>
        </div>

      </div>
    </section>
  )
}


