"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import CountUp from "@/components/shared/CountUp"
import PartnersMarquee from "@/components/shared/PartnersMarquee"

export default function CompanyPage() {
  const [isVisible, setIsVisible] = useState(false)
  const [isPlaying, setIsPlaying] = useState(false)

  useEffect(() => {
    setIsVisible(true)
  }, [])

  return (
    <main className="bg-white overflow-x-hidden">

      {/* Hero Banner */}
      <section
        className="relative min-h-[50vh] md:h-[60vh] flex items-center justify-center text-center px-6 overflow-hidden"
      >
        {/* Background Image with Overlay */}
        <div className="absolute inset-0 z-0">
          <div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/80 to-black/70 z-10" />
          <img src="/images/corporate-team.png" alt="Company Hero" className="w-full h-full object-cover" />
        </div>

        {/* Neon Glow Line */}
        <div
          className="absolute bottom-0 left-0 right-0 h-1 z-[2]"
          style={{
            background: "linear-gradient(90deg, transparent 0%, #05033e 50%, transparent 100%)",
            boxShadow: "0 0 20px #05033e, 0 0 40px #05033e"
          }}
        />

        <div className={`relative z-10 transition-all duration-1000 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"}`}>
          <h1 className="text-white text-4xl md:text-6xl font-bold mb-4">
            Shynr <span style={{ color: "#96c2ecff", textShadow: "0 0 20px rgba(5,3,62,0.3)" }}>Profile</span>
          </h1>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Building scalable workforces. Empowering businesses.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-24">
        <div className="max-w-7xl mx-auto px-6 grid md:grid-cols-2 gap-16">

          {/* Left */}
          <div className="space-y-6 text-2xl font-bold leading-tight text-foreground">
            <p className="border-l-4 border-[#05033e] pl-4">About SHYNR Private Limited</p>
            <p className="border-l-4 border-gray-200 pl-4">To become a trusted national workforce solutions partner</p>
            <p className="border-l-4 border-gray-200 pl-4">Delivering recruitment & managed services</p>
          </div>

          {/* Right */}
          <div className="text-muted-foreground space-y-6 leading-relaxed text-lg">
            <p>
              SHYNR Private Limited is a fast-growing business services organization delivering
              recruitment, workforce solutions, and managed services to clients across BFSI, IT/ITES,
              Retail, E-commerce, Telecom, and Education sectors.
            </p>

            <p>
              Backed by domain expertise and process-driven execution, SHYNR partners with organizations
              to build scalable, compliant, and high-performance workforces.
            </p>

            <p>
              Our Vision is to enable organizations to grow efficiently through reliable talent
              and technology-driven HR services.
            </p>
          </div>

        </div>
      </section>


      {/* Feature Section */}
      <section className="bg-white py-24">
        <div className="max-w-7xl mx-auto px-6 grid md:grid-cols-2 gap-16 items-center">

          {/* Image Placeholder */}
          <div className="rounded-3xl overflow-hidden h-[420px] shadow-2xl relative group">
            <div className="absolute inset-0 bg-background/20 group-hover:bg-transparent transition-colors z-10" />
            {/* Header Image: Generated by AI (saved as /public/images/partnership.png) */}
            <img
              src="/images/partnership.png"
              alt="Strategic Partnership"
              className="w-full h-full object-cover transition-transform duration-1000"
            />
          </div>

          {/* Content */}
          <div>
            <h2 className="text-4xl font-bold mb-6 text-foreground">
              Why <span style={{ color: "#05033e", textShadow: "0 2px 10px rgba(5,3,62,0.2)" }}>SHYNR?</span> <br />
              Integrity & Excellence
            </h2>

            <p className="text-gray-600 mb-8 text-lg">
              We blend people, process, and technology to deliver workforce solutions that are
              flexible, compliant, and aligned with client business objectives. Our operational strength
              and consistent growth reflect trust and delivery capability.
            </p>

            <div className="flex items-center gap-6 mb-12">
              <Link
                href="/contactUs"
                className="px-8 py-3 rounded-md font-bold transition-all duration-300 border border-transparent hover:border-[#05033e] bg-[#05033e] text-white hover:bg-white hover:text-[#05033e] inline-block text-center"
              >
                Partner With Us
              </Link>

              <Link href="/services/digital_platform" className="text-foreground font-bold hover:text-[#05033e] transition-colors inline-block">
                Learn more →
              </Link>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {[
                { value: 25, suffix: "+", label: "Companies Served" },
                { value: 15000, suffix: "+", label: "Professionals Hired" },
                { value: 28, suffix: "", label: "States Covered" },
                { value: 100, suffix: "%", label: "Compliance" }
              ].map((stat) => (
                <div key={stat.label}>
                  <h3 className="text-3xl font-bold" style={{ color: "#05033e" }}>
                    <CountUp end={stat.value} suffix={stat.suffix} />
                  </h3>
                  <p className="text-gray-800 font-semibold mt-1">
                    {stat.label}
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    Delivering impact
                  </p>
                </div>
              ))}
            </div>
          </div>

        </div>
      </section>



      {/* Partners Marquee */}
      <PartnersMarquee />

      {/* How it works */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6 text-center">

          <h2 className="text-4xl font-bold mb-4 text-foreground">
            Our Approach
          </h2>

          <p className="max-w-2xl mx-auto text-gray-600 mb-16 text-lg">
            A systematic 4-step process to ensure quality and compliance in workforce deployment.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-10 mb-24">
            {[
              { title: "Understand", desc: "Deep dive into client requirements and business objectives." },
              { title: "Source", desc: "Leverage our vast network and digital sourcing channels." },
              { title: "Screen", desc: "Rigorous evaluation and quality-focused shortlisting." },
              { title: "Deploy", desc: "Seamless onboarding with compliance and payroll support." },
            ].map((step, i) => (
              <div key={step.title} className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-2xl hover:border-[#05033e] border border-transparent transition-all duration-300 group">
                <div
                  className="w-14 h-14 mx-auto mb-6 rounded-full flex items-center justify-center font-bold text-xl transition-colors group-hover:bg-[#05033e] group-hover:text-foreground"
                  style={{
                    backgroundColor: `hsl(210, 100%, ${96 - (i % 3) * 2}%)`,
                    color: "#05033e",
                    borderColor: "#05033e",
                    borderWidth: "1px"
                  }}
                >
                  {i + 1}
                </div>
                <h3 className="font-bold mb-3 text-xl">{step.title}</h3>
                <p className="text-gray-600 text-sm">{step.desc}</p>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* Video Section */}
      <section className="pb-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">

          <div
            className="relative rounded-3xl overflow-hidden bg-background min-h-[400px] flex items-center justify-center border border-border cursor-pointer group"
            onClick={() => setIsPlaying(true)}
          >

            {!isPlaying ? (
              <>
                {/* Placeholder Background for Video */}
                {/* Placeholder Background for Video */}
                <div className="absolute inset-0 bg-[#e0e7ff] opacity-30 transition-opacity group-hover:opacity-40"></div>

                {/* Center content */}
                <div className="relative z-10 flex flex-col items-center justify-center text-white px-6 text-center pointer-events-none">
                  <button
                    className="w-20 h-20 rounded-full flex items-center justify-center mb-8 transition group-hover:shadow-[0_0_40px_rgba(5,3,62,0.7)] shadow-[0_0_30px_rgba(5,3,62,0.5)]"
                    style={{ backgroundColor: "#05033e", color: "white" }}
                  >
                    <span className="text-3xl ml-1">▶</span>
                  </button>

                  <h2 className="text-3xl md:text-5xl font-bold leading-tight mb-4 text-foreground">
                    Reliable Workforce Backed By <br />
                    <span style={{ color: "#05033e" }}>Strong Governance</span>
                  </h2>
                </div>
              </>
            ) : (
              <video
                src="" // Placeholder: Add your video URL here
                controls
                autoPlay
                className="absolute inset-0 w-full h-full object-cover"
                style={{ backgroundColor: "#000" }}
              >
                Your browser does not support the video tag.
              </video>
            )}

          </div>
        </div>
      </section>

    </main>
  )
}
