export interface Job {
    _id: string;
    logo?: string;
    title: string;
    company: string;
    category: string;
    type: string;
    salary: string;
    location: string;
    description?: string;
    responsibilities?: string[];
    skills?: string[];
    postedDate?: string;
    experience?: string;
    degree?: string;
}

export const mockJobs: Job[] = [
    {
        _id: "1",
        title: "Senior Product Designer",
        company: "Tech Corp",
        category: "Design",
        type: "Full Time",
        salary: "$120k",
        location: "San Francisco, CA",
        logo: "https://logo.clearbit.com/stripe.com",
        postedDate: "2 days ago",
        experience: "5 Years",
        degree: "Bachelor",
        description: "We are looking for a Senior Product Designer to join our team. You will be responsible for defining the user experience for our products.",
        responsibilities: [
            "Lead design projects from concept to launch",
            "Collaborate with product management and engineering",
            "Conduct user research and usability testing",
            "Mentor junior designers"
        ],
        skills: ["Figma", "Prototyping", "User Research", "UI/UX"]
    },
    {
        _id: "2",
        title: "Frontend Developer",
        company: "WebSolutions",
        category: "Development",
        type: "Remote",
        salary: "$110k",
        location: "Remote",
        logo: "https://logo.clearbit.com/vercel.com",
        postedDate: "1 week ago",
        experience: "3 Years",
        degree: "Bachelor",
        description: "Join our frontend team to build modern web applications using React and Next.js.",
        responsibilities: [
            "Develop new features using React and TypeScript",
            "Optimize application for maximum speed",
            "Collaborate with backend developers",
            "Ensure high-quality graphic standards"
        ],
        skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"]
    },
    {
        _id: "3",
        title: "Marketing Manager",
        company: "Growth Inc",
        category: "Marketing",
        type: "Part Time",
        salary: "$60k",
        location: "New York, NY",
        logo: "https://logo.clearbit.com/google.com",
        postedDate: "3 days ago",
        experience: "4 Years",
        degree: "Master",
    },
    {
        _id: "4",
        title: "UX Researcher",
        company: "Creative Studio",
        category: "Design",
        type: "Contract",
        salary: "$80k",
        location: "Austin, TX",
        logo: "https://logo.clearbit.com/airbnb.com",
        postedDate: "Just now",
        experience: "2 Years",
        degree: "Bachelor",
    },
    {
        _id: "5",
        title: "Backend Engineer",
        company: "DataFlow",
        category: "Development",
        type: "Full Time",
        salary: "$140k",
        location: "Seattle, WA",
        logo: "https://logo.clearbit.com/amazon.com",
        postedDate: "1 month ago",
        experience: "6 Years",
        degree: "Master",
    },
    {
        _id: "6",
        title: "Project Manager",
        company: "BuildIt",
        category: "Management",
        type: "Full Time",
        salary: "$120k",
        location: "Chicago, IL",
        logo: "https://logo.clearbit.com/asana.com",
        postedDate: "5 days ago",
        experience: "5 Years",
        degree: "Bachelor",
    },
    {
        _id: "7",
        title: "Customer Success Lead",
        company: "HelpDesk",
        category: "Customer Service",
        type: "Full Time",
        salary: "$70k",
        location: "Remote",
        logo: "https://logo.clearbit.com/zendesk.com",
        postedDate: "2 weeks ago",
        experience: "3 Years",
        degree: "Bachelor",
    },
    {
        _id: "8",
        title: "Financial Analyst",
        company: "MoneyMatters",
        category: "Finance",
        type: "Full Time",
        salary: "$90k",
        location: "London, UK",
        logo: "https://logo.clearbit.com/revolut.com",
        postedDate: "1 day ago",
        experience: "2 Years",
        degree: "Master",
    },
    {
        _id: "9",
        title: "Senior React Dev",
        company: "CodeFactory",
        category: "Development",
        type: "Contract",
        salary: "$100k",
        location: "Remote",
        logo: "https://logo.clearbit.com/github.com",
        postedDate: "3 days ago",
        experience: "4 Years",
        degree: "Bachelor",
    },
    {
        _id: "10",
        title: "Art Director",
        company: "Visionary",
        category: "Design",
        type: "Full Time",
        salary: "$130k",
        location: "New York, NY",
        logo: "https://logo.clearbit.com/adobe.com",
        postedDate: "1 week ago",
        experience: "8 Years",
        degree: "Master",
    },
    {
        _id: "11",
        title: "DevOps Engineer",
        company: "CloudNet",
        category: "Development",
        type: "Full Time",
        salary: "$150k",
        location: "Austin, TX",
        logo: "https://logo.clearbit.com/aws.amazon.com",
        postedDate: "4 days ago",
        experience: "5 Years",
        degree: "Bachelor",
    },
    {
        _id: "12",
        title: "Social Media Manager",
        company: "BuzzFeed",
        category: "Marketing",
        type: "Part Time",
        salary: "$40k",
        location: "Los Angeles, CA",
        logo: "https://logo.clearbit.com/twitter.com",
        postedDate: "Just now",
        experience: "1 Year",
        degree: "Bachelor",
    },
    {
        _id: "13",
        title: "HR Specialist",
        company: "PeopleFirst",
        category: "Management",
        type: "Full Time",
        salary: "$65k",
        location: "Chicago, IL",
        logo: "https://logo.clearbit.com/workday.com",
        postedDate: "6 days ago",
        experience: "3 Years",
        degree: "Bachelor",
    },
    {
        _id: "14",
        title: "Data Scientist",
        company: "BigData",
        category: "Development",
        type: "Full Time",
        salary: "$160k",
        location: "San Francisco, CA",
        logo: "https://logo.clearbit.com/databricks.com",
        postedDate: "2 weeks ago",
        experience: "4 Years",
        degree: "Master",
    },
    {
        _id: "15",
        title: "Support Agent",
        company: "ServiceNow",
        category: "Customer Service",
        type: "Remote",
        salary: "$50k",
        location: "Remote",
        logo: "https://logo.clearbit.com/servicenow.com",
        postedDate: "1 day ago",
        experience: "0-1 Years",
        degree: "None",
    },
];
